---
name: Nicknames
version: 3.1.0
api: 3.0.0
main: Nick2\Nick
author: ElektroPrinz & Sub-Author is Jes'kad Ad'aryc (Lets face it, I, Kad, have done most of the fixing here lmao)
description: Adds Nicknames to your server.
permissions:
  nick.help:
    default: true
  nick.set:
    default: true
  nick.reset:
    default: true
  nick.see:
    default: op
  nick.admin.set:
    default: op
  nick.admin.reset:
    default: op
commands:
  nick:
    description: Nick main command
    usage: /nick <sub-command>
    permission: nick.help
...
