---
name: Nickname
version: 3.1.0
api: 3.15.0
main: Nickname\Nick
author: ElektroPrinz
authors: [ElektroPrinz, KadTheHunter]
description: Nickname plugin for PocketMine-MP
depend: [PureChat]
commands:
  nick:
    description: Nick main command
    usage: /nick <sub-command>
    permission: nick.help
...
