---
# Config file for Nick
# Nick (c) 2016 AryToNeX
# Edited by ElektroPrinz
# Edited more and fixed up by Jes'kad Ad'aryc (LegoFan48737)

# Keeps the nick after leave/login/server closed/thermonuclear war
# Boolean parameter (true, false)
keep-nick: true

# Commands
# Here you can customize commands and descriptions!

help-command: "help" # No description for it *sad help command*

set-command: "set"
set-usage: "<nick>"
set-description: "Set a nick"
set-admin-usage: "<nick> <player>"
set-admin-description: "Sets a nick to another player"

reset-command: "reset"
reset-description: "Return to your real name"
reset-admin-usage: "<player>"
reset-admin-description: "Resets a player's nick"

see-command: "see"
see-usage: "<player nick> OR <player name>"
see-description: "See the real name of a player or if a player has a nick set"

# Messages
# Here you can customize messages!

# No permission
no-permission-help: "§cYou don't have permission to use /nick help!"
no-permission-set: "§cYou don't have permission to set a nickname!"
no-permission-admin-set: "§cYou don't have permission to set a nickname on another player!"
no-permission-reset: "§cYou don't have permission to reset your nickname!"
no-permission-admin-reset: "§cYou don't have the permission to reset other players nicknames!"
no-permission-see: "§cYou don't have the permission to see other players real usernames!"

# Various errors
player-not-online: "§ePlayer is not online!"
must-specify-player: "§eYou must specify a player!"
must-specify-nick: "§eYou must specify a nickname!"
no-subcommand: "§eNo subcommands defined. Please run §a/nick help§e for the subcommand list."
no-run-in-console: "§eAll commands must be used in-game!"

# Help page
help-header: "§eNick -- Help"
help-command-color: "§e"
help-usage-color: "§a"
help-two-points-color: "§f"
help-description-color: "§f"

# Set
set: "§aNick successfully set"
set-by-admin: "§eAn Admin set your Nickname!"

# Reset
reset: "§aNick successfully resetted!"
reset-by-admin: "§eAn Admin reset your Nickname!"

# See
see: "§a{player_nick}§e's real name is §a{player_name}"
see-no-nick: "§eThat player has no Nickname!"
...
